/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.controller;

import io.swagger.exception.BadRequestException;
import io.swagger.model.account.AccountGetDTO;
import io.swagger.model.entity.Account;
import io.swagger.model.account.AccountPatchDTO;
import io.swagger.model.account.AccountPostDTO;
import io.swagger.model.utils.DTOEntity;
import io.swagger.model.utils.Error;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-05-05T18:12:07.854Z[GMT]")
@Validated
public interface AccountControllerInterface {

    @Operation(summary = "Creates a primary or secondary account", description = "Creates a primary or savings account for provided user_id.", security = {
            @SecurityRequirement(name = "bearerAuth")    }, tags={ "accounts" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Created", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AccountGetDTO.class))),

            @ApiResponse(responseCode = "400", description = "The request was invalid or cannot be served."),

            @ApiResponse(responseCode = "401", description = "Credentials invalid or missing."),

            @ApiResponse(responseCode = "403", description = "You are not authorized to make this request."),

            @ApiResponse(responseCode = "404", description = "Resource not found."),

            @ApiResponse(responseCode = "409", description = "There was a conflict processing your request."),

            @ApiResponse(responseCode = "500", description = "Internal server error.") })
    @RequestMapping(value = "/api/accounts",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.POST)
    ResponseEntity<AccountGetDTO> createAccount(@Parameter(in = ParameterIn.DEFAULT, description = "Created User object", required=true, schema=@Schema()) @Valid @RequestBody AccountPostDTO body) throws Exception;


    @Operation(summary = "Alters limit or status of Account", description = "", security = {
            @SecurityRequirement(name = "bearerAuth")    }, tags={ "accounts" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Success", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AccountGetDTO.class))),

            @ApiResponse(responseCode = "400", description = "The request was invalid or cannot be served."),

            @ApiResponse(responseCode = "401", description = "Credentials invalid or missing."),

            @ApiResponse(responseCode = "403", description = "You are not authorized to make this request."),

            @ApiResponse(responseCode = "404", description = "Resource not found."),

            @ApiResponse(responseCode = "500", description = "Internal server error.") })
    @RequestMapping(value = "/api/accounts/{iban}",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.PATCH)
    ResponseEntity<AccountGetDTO> editAccount(@Parameter(in = ParameterIn.PATH, description = "Iban of account", required=true, schema=@Schema()) @PathVariable("iban") String iban, @Parameter(in = ParameterIn.DEFAULT, description = "Edit information", required=true, schema=@Schema()) @Valid @RequestBody AccountPatchDTO body);

    @Operation(summary = "Finds an Account based on iban", description = "Returns an account matching the provided iban.", security = {
            @SecurityRequirement(name = "bearerAuth")    }, tags={ "accounts" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Success", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AccountGetDTO.class))),

            @ApiResponse(responseCode = "400", description = "The request was invalid or cannot be served."),

            @ApiResponse(responseCode = "401", description = "Credentials invalid or missing."),

            @ApiResponse(responseCode = "403", description = "You are not authorized to make this request."),

            @ApiResponse(responseCode = "404", description = "Resource not found."),

            @ApiResponse(responseCode = "500", description = "Internal server error.") })
    @RequestMapping(value = "/api/accounts/{iban}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<AccountGetDTO> getAccountByIban(@Parameter(in = ParameterIn.PATH, description = "Iban of account", required=true, schema=@Schema()) @PathVariable("iban") String iban);


    @Operation(summary = "Finds own Account by default, otherwise by provided user_id", description = "Returns a list of accounts, optionally filtered by parameters.", security = {
            @SecurityRequirement(name = "bearerAuth")    }, tags={ "accounts" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Success", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AccountGetDTO.class)))),

            @ApiResponse(responseCode = "400", description = "The request was invalid or cannot be served."),

            @ApiResponse(responseCode = "401", description = "Credentials invalid or missing."),

            @ApiResponse(responseCode = "403", description = "You are not authorized to make this request."),

            @ApiResponse(responseCode = "404", description = "Resource not found."),

            @ApiResponse(responseCode = "500", description = "Internal server error.") })
    @RequestMapping(value = "/api/accounts",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Page<AccountGetDTO>> getAccounts(@Parameter(in = ParameterIn.QUERY, description = "This query will get both accounts that belong to the matching user id." ,schema=@Schema()) @Valid @RequestParam(value = "user_id", required = false) String userId, @Parameter(in = ParameterIn.QUERY, description = "This query will filter either the 'primary' or 'savings' account." ,schema=@Schema(allowableValues={ "primary", "savings" }
    )) @Valid @RequestParam(value = "type", required = false) List<String> type, @Parameter(in = ParameterIn.QUERY, description = "This query will filter for a page" ,schema=@Schema()) @Valid @RequestParam(value = "page", defaultValue = "0", required = false) Integer page, @Parameter(in = ParameterIn.QUERY, description = "This query is the number of items returned" ,schema=@Schema()) @Valid @RequestParam(value = "size", defaultValue = "5", required = false) Integer size);
}

